# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/





#        source: [
 #             {id: 'gb', text: 'Great Britain'},
  #            {id: 'us', text: 'United States'},
   #           {id: 'ru', text: 'Russia'}
    #       ],


	$('#country').editable
  value: 'California'
  typeahead:
    name: 'course_id'
    value: '2'
    url:   'courses/follow' 
    local: [
      'Alabama'
      'Alaska'
      'Arizona'
      'Arkansas'
      'California'
      'Colorado'
      'Connecticut'
      'Delaware'
      'Florida'
      'Georgia'
      'Hawaii'
      'Idaho'
      'Illinois'
      'Indiana'
      'Iowa'
      'Kansas'
      'Kentucky'
      'Louisiana'
      'Maine'
      'Maryland'
      'Massachusetts'
      'Michigan'
      'Minnesota'
      'Mississippi'
      'Missouri'
      'Montana'
      'Nebraska'
      'Nevada'
      'New Hampshire'
      'New Jersey'
      'New Mexico'
      'New York'
      'North Dakota'
      'North Carolina'
      'Ohio'
      'Oklahoma'
      'Oregon'
      'Pennsylvania'
      'Rhode Island'
      'South Carolina'
      'South Dakota'
      'Tennessee'
      'Texas'
      'Utah'
      'Vermont'
      'Virginia'
      'Washington'
      'West Virginia'
      'Wisconsin'
      'Wyoming'
    ]

# ---
# generated by js2coffee 2.1.0
